# Generated by Django 5.1.6 on 2025-02-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="authour",
            new_name="author",
        ),
    ]
